# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
sudo: required

# Note: travis currently does not support listing more than one language so
# this cheats and claims to only be ruby (to allow rvm variable).  If they add
# multiple language support, this should probably get updated to install steps
# and/or rvm/gemfile/jdk/etc. entries rather than manually doing the work.
#
# Modeled after:
# https://github.com/google/protobuf/blob/master/.travis.yml
language: ruby
# Work around segmentation fault in CocoaPods on default Ruby (2.0.0).
# https://docs.travis-ci.com/user/common-build-problems/#CocoaPods-fails-with-a-segmentation-fault
rvm: 2.2.3

os:
- osx
- linux
osx_image: xcode7.2
dist: trusty

before_install:
- openssl aes-256-cbc -K $encrypted_49d9325ac449_key -iv $encrypted_49d9325ac449_iv
  -in client-secret.json.enc -out client-secret.json -d || true

script:
- ./travis.sh $CONFIG
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS=${TRAVIS_BUILD_DIR}/client-secret.json
  matrix:
  - CONFIG=android_jdk8
  - CONFIG=android_oracle8
  - CONFIG=go
  - CONFIG=java_jdk8
  - CONFIG=java_oracle8
  - CONFIG=php
matrix:
  exclude:
  # It's nontrivial to programmatically install a new JDK from the command
  # line on OS X, so we rely on testing on Linux for Java code.
  - os: osx
    env: CONFIG=android_jdk8
  - os: osx
    env: CONFIG=android_oracle8
  - os: osx
    env: CONFIG=java_jdk8
  - os: osx
    env: CONFIG=java_oracle8
  # Add into the matrix OS X tests of iOS samples (needs Xcode, so it won't
  # work on other platforms). These are split so it doesn't take as long to run
  include:
  - os: osx
    env: CONFIG=objectivec_ios
  - os: osx
    env: CONFIG=swift_ios

branches:
  only:
  - master
notifications:
  email: false
